version: "3.7"
services:
  ndvi-flask:
    image: silasnascimento/ndvi-flask-app:latest
    deploy:                      # ✅ Correto para Swarm
      resources:
        limits:
          cpus: "1"
          memory: 1024M
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:                    # ✅ Labels Traefik corretos
        - "traefik.enable=true"
        - "traefik.http.routers.ndvi-flask.rule=Host(`ndvi.planoagro.com.br`)"
        - "traefik.http.routers.ndvi-flask.entrypoints=websecure"
        - "traefik.http.routers.ndvi-flask.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.ndvi-flask.loadbalancer.server.port=5000"
    environment:
      GEE_PROJECT: "ee-contatoplanoagro"
      FLASK_ENV: "production"
    command: >                   # ✅ Gunicorn para produção
      sh -c "pip install --no-cache-dir gunicorn && gunicorn --bind 0.0.0.0:5000 --workers 2 --threads 2 --timeout 120 app:app"
    volumes:
      - earthengine:/root/.config/earthengine  # ⚠️ Falta :ro
    networks:
      - network_swarm_public     # ✅ Rede correta

volumes:
  earthengine:
    external: true

networks:
  network_swarm_public:
    external: true