version: '3.8'

services:
  ndvi-flask:
    image: silasnascimento/ndvi-flask-app:latest
    container_name: appgee-flask
    ports:
      - "5000:5000"
    environment:
      - GEE_PROJECT=${GEE_PROJECT:-ee-silasnascimento}
    volumes:
      - gee-credentials:/root/.config/earthengine/credentials:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  gee-credentials:
    external: true
    name: gee-credentials-${GEE_PROJECT:-silasnascimento}
